stages:
  - build-push

build-push:
  image: google/cloud-sdk:alpine
  stage: build-push
  services:
    - docker:18.09.7-dind
  variables:
    ENV_BUILD: staging
    DOCKER_IMAGE_GCR: $GCR_STORAGE_HOST/$GCR_STORAGE_PROJECT/$ENV_BUILD/$CI_PROJECT_NAMESPACE/$CI_PROJECT_NAME:$CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
  script:
    - echo ${GCR_STORAGE_KEY} | base64 -d  > ${HOME}/gcloud-service-key.json
    - gcloud --quiet --no-user-output-enabled auth activate-service-account --key-file=${HOME}/gcloud-service-key.json
    - gcloud --quiet --no-user-output-enabled config set project ${GCR_STORAGE_PROJECT}
    - gcloud --quiet --no-user-output-enabled auth configure-docker
    - docker build -t ${DOCKER_IMAGE_GCR} .
    - docker push ${DOCKER_IMAGE_GCR}
  only:
    - sandbox

build-push-old-staging:
  image: docker:latest
  stage: build-push
  services:
    - docker:dind
  environment: old-staging
  script:
    - make build-and-push
    - make deploy
  only:
    - sandbox
  tags:
    - old-staging
