include:
  - project: platform/gitlab-ci
    file: /apps/gitlab-ssh-keys.yml
  - project: platform/gitlab-ci
    file: /apps/gcr-push.yml

stages:
  - push

push-gcr-stag:
  stage: push
  extends:
    - .gcr-push
  variables:
    ENV_BUILD: staging
    DOCKER_TAG: $CI_COMMIT_SHORT_SHA-$CI_PIPELINE_ID
    DOCKERFILE_PATH: Dockerfile
    APP_NAME: $CI_PROJECT_NAME
    APP_PATH: '.'
  only:
    - staging
