image: docker:latest

services:
  - docker:dind

before_script:
  - sudo apt install curl

stages:
  - build
  - deploy
  - checking
  - notify-failure

variables:
  URL_PIPELINE: $CI_PIPELINE_URL

build:
  stage: build
  environment: staging
  script:
    - make slack-notify-start
    - make build-and-push
  only:
    - develop

deploy:
  stage: deploy
  needs:
    - job: build
  environment: staging
  script:
    - make deploy
    - make slack-notify-finish
  only:
    - develop

checking:
  stage: checking
  needs:
    - job: deploy
  environment: staging
  script:
    - make health-check
  only:
    - develop

notify-failure:
  stage: notify-failure
  environment: staging
  script:
    - make slack-notify-failed
  only:
    - develop
  when: on_failure
