export const EmployeeRoleSeed = [
  {
    id: 'bf5ee1d4-5955-4228-b866-9a23fcdf4f01',
    employeeRoleId: 232,
    employeeRoleIdParent: 0,
    employeeRoleCode: 'ACOF',
    employeeRoleName: 'Accounting Officer',
    employeeLevel: 'section_head',
    employeePosition: '',
    description: '-',
    isHasVoucher: false,
    isDeleted: false,
  },
  {
    id: '940c3817-9951-4feb-8a36-07bf7bdeff79',
    employeeRoleId: 275,
    employeeRoleIdParent: 0,
    employeeRoleCode: 'STAFF_ACC',
    employeeRoleName: 'Staff Accounting',
    employeeLevel: 'staff',
    employeePosition: '',
    description: '-',
    isHasVoucher: false,
    isDeleted: false,
  },
  {
    id: '6b4bb732-9a9b-4a81-ac2e-f8819c45c9d2',
    employeeRoleId: 307,
    employeeRoleIdParent: null,
    employeeRoleCode: 'ADMN',
    employeeRoleName: 'Admin',
    employeeLevel: 'staff',
    employeePosition: 'staff',
    description: '-',
    isHasVoucher: false,
    isDeleted: false,
  },
  {
    id: '58ed56eb-1ad3-41d7-a42f-61834e88ea35',
    employeeRoleId: 310,
    employeeRoleIdParent: null,
    employeeRoleCode: 'ADPO',
    employeeRoleName: 'Admin Operational COD (Cash On Delivery)',
    employeeLevel: 'staff',
    employeePosition: 'staff',
    description: '-',
    isHasVoucher: false,
    isDeleted: false,
  },
  {
    id: 'ef01ffb4-c0f9-4dcc-8c68-9648942f8362',
    employeeRoleId: 468,
    employeeRoleIdParent: null,
    employeeRoleCode: 'AOFM',
    employeeRoleName: 'Admin Operational First Mile',
    employeeLevel: 'staff',
    employeePosition: 'staff',
    description: '-',
    isHasVoucher: false,
    isDeleted: false,
  },
  {
    id: 'f1b06a49-c09e-43e7-9ac0-0c5dbc072ba5',
    employeeRoleId: 483,
    employeeRoleIdParent: 482,
    employeeRoleCode: 'SLM',
    employeeRoleName: 'Last Mile Sigesit',
    employeeLevel: '',
    employeePosition: '',
    description: '-',
    isHasVoucher: false,
    isDeleted: false,
  },
  {
    id: '4a1cc750-37f7-48f6-9ff1-6022bfbf76bd',
    employeeRoleId: 487,
    employeeRoleIdParent: 482,
    employeeRoleCode: 'DRV_LM',
    employeeRoleName: 'Last Mile Driver',
    employeeLevel: '',
    employeePosition: '',
    description: '-',
    isHasVoucher: false,
    isDeleted: false,
  },
  {
    id: '6f6dce77-97dd-46c5-8891-d11a68ce6fd1',
    employeeRoleId: 728,
    employeeRoleIdParent: 727,
    employeeRoleCode: 'MGR_ACC',
    employeeRoleName: 'Manager Accounting',
    employeeLevel: '',
    employeePosition: '',
    description: '-',
    isHasVoucher: false,
    isDeleted: false,
  },
  {
    id: 'c03f845a-e84d-41ed-bcf6-74fe7109b5f9',
    employeeRoleId: 729,
    employeeRoleIdParent: 728,
    employeeRoleCode: 'SPV_ACC',
    employeeRoleName: 'Supervisor Accounting',
    employeeLevel: '',
    employeePosition: '',
    description: '-',
    isHasVoucher: false,
    isDeleted: false,
  },
  {
    id: '61c7c0a2-c81b-4877-a281-e316d9954e9c',
    employeeRoleId: 750,
    employeeRoleIdParent: 1447,
    employeeRoleCode: 'SPV_BRCO',
    employeeRoleName: 'Supervisor Branch Controller',
    employeeLevel: '',
    employeePosition: '',
    description: '-',
    isHasVoucher: false,
    isDeleted: false,
  },
  {
    id: '8f3be96f-a88d-4f62-ae88-3cf2abc05cd0',
    employeeRoleId: 907,
    employeeRoleIdParent: 751,
    employeeRoleCode: 'ADM_FNC',
    employeeRoleName: 'Admin Finance',
    employeeLevel: '',
    employeePosition: '',
    description: '-',
    isHasVoucher: false,
    isDeleted: false,
  },
  {
    id: '17b8d360-ce3f-401f-8173-da9d371fb026',
    employeeRoleId: 923,
    employeeRoleIdParent: 1086,
    employeeRoleCode: 'SLM_SDS',
    employeeRoleName: 'SDS Sigesit Last Mile',
    employeeLevel: '',
    employeePosition: '',
    description: '-',
    isHasVoucher: false,
    isDeleted: false,
  },
  {
    id: 'c1ab5326-3bbc-4cbc-8aec-800a4e1b82f9',
    employeeRoleId: 925,
    employeeRoleIdParent: 743,
    employeeRoleCode: 'SSTAFF_TAX',
    employeeRoleName: 'Senior Staff Tax',
    employeeLevel: '',
    employeePosition: '',
    description: '-',
    isHasVoucher: false,
    isDeleted: false,
  },
  {
    id: '4c4a92ce-3a9b-4f7e-b09f-f0a6eefb8799',
    employeeRoleId: 1375,
    employeeRoleIdParent: 1126,
    employeeRoleCode: 'STAFF_IT_QE',
    employeeRoleName: 'Staff IT QA Engineering',
    employeeLevel: '',
    employeePosition: '',
    description: '-',
    isHasVoucher: false,
    isDeleted: false,
  },
];
