import { User } from '../model/user.entity';
import * as uuid from 'uuid';

const genId = () => {
  return uuid.v4();
}

export const UserSeed = [
  {
    id: '3aa3eac8-a62f-44c3-b53c-31372492f9a0',
    userId: 15,
    employeeId: 2981,
    firstName: 'Adry',
    lastName: 'Adry',
    username: 'adry',
    password: 'd8578edf8458ce06fbc5bb76a58c5ca4',
    loginCount: 1,
    loginAttemptError: null,
    lastLogin: null,
    userIdCreated: 1,
    createdTime: new Date(),
    userIdUpdated: 1,
    updatedTime: new Date(),
    isDeleted: false,
    email: 'adry@sicepat.com',
    passwordReset: null,
    otpReset: null,
  },
  {
    id: genId(),
    userId: 17,
    employeeId: 2983,
    firstName: 'Super',
    lastName: 'User',
    username: 'superuser',
    password: 'd8578edf8458ce06fbc5bb76a58c5ca4',
    loginCount: 1,
    loginAttemptError: null,
    lastLogin: null,
    userIdCreated: 1,
    createdTime: new Date(),
    userIdUpdated: 1,
    updatedTime: new Date(),
    isDeleted: false,
    email: 'superuser@sicepat.com',
    passwordReset: null,
    otpReset: null,
  },
  {
    id: genId(),
    userId: 16,
    employeeId: 2982,
    firstName: 'Accounting',
    lastName: 'Accounting',
    username: 'accounting',
    password: 'd8578edf8458ce06fbc5bb76a58c5ca4',
    loginCount: 1,
    loginAttemptError: null,
    lastLogin: null,
    userIdCreated: 1,
    createdTime: new Date(),
    userIdUpdated: 1,
    updatedTime: new Date(),
    isDeleted: false,
    email: 'accounting@sicepat.com',
    passwordReset: null,
    otpReset: null,
  },
  {
    id: genId(),
    userId: 16,
    employeeId: 2982,
    firstName: 'PIC',
    lastName: 'HO',
    username: 'pic_ho',
    password: 'd8578edf8458ce06fbc5bb76a58c5ca4',
    loginCount: 1,
    loginAttemptError: null,
    lastLogin: null,
    userIdCreated: 1,
    createdTime: new Date(),
    userIdUpdated: 1,
    updatedTime: new Date(),
    isDeleted: false,
    email: 'pic_ho@sicepat.com',
    passwordReset: null,
    otpReset: null,
  },
  {
    id: genId(),
    userId: 16,
    employeeId: 2982,
    firstName: 'SS',
    lastName: 'HO',
    username: 'ss_ho',
    password: 'd8578edf8458ce06fbc5bb76a58c5ca4',
    loginCount: 1,
    loginAttemptError: null,
    lastLogin: null,
    userIdCreated: 1,
    createdTime: new Date(),
    userIdUpdated: 1,
    updatedTime: new Date(),
    isDeleted: false,
    email: 'ss_ho@sicepat.com',
    passwordReset: null,
    otpReset: null,
  },
  {
    id: genId(),
    userId: 16,
    employeeId: 2982,
    firstName: 'SPV',
    lastName: 'HO',
    username: 'spv_ho',
    password: 'd8578edf8458ce06fbc5bb76a58c5ca4',
    loginCount: 1,
    loginAttemptError: null,
    lastLogin: null,
    userIdCreated: 1,
    createdTime: new Date(),
    userIdUpdated: 1,
    updatedTime: new Date(),
    isDeleted: false,
    email: 'spv_ho@sicepat.com',
    passwordReset: null,
    otpReset: null,
  },
  {
    id: genId(),
    userId: 17,
    employeeId: 2983,
    firstName: 'Admin',
    lastName: 'Branch',
    username: 'admin',
    password: 'd8578edf8458ce06fbc5bb76a58c5ca4',
    loginCount: 1,
    loginAttemptError: null,
    lastLogin: null,
    userIdCreated: 1,
    createdTime: new Date(),
    userIdUpdated: 1,
    updatedTime: new Date(),
    isDeleted: false,
    email: 'adminbranch@sicepat.com',
    passwordReset: null,
    otpReset: null,
  },
  {
    id: genId(),
    userId: 16,
    employeeId: 2982,
    firstName: 'OPS',
    lastName: 'OPS',
    username: 'ops',
    password: 'd8578edf8458ce06fbc5bb76a58c5ca4',
    loginCount: 1,
    loginAttemptError: null,
    lastLogin: null,
    userIdCreated: 1,
    createdTime: new Date(),
    userIdUpdated: 1,
    updatedTime: new Date(),
    isDeleted: false,
    email: 'ops@sicepat.com',
    passwordReset: null,
    otpReset: null,
  },
  {
    id: genId(),
    userId: 16,
    employeeId: 2982,
    firstName: 'TAX',
    lastName: 'TAX',
    username: 'tax',
    password: 'd8578edf8458ce06fbc5bb76a58c5ca4',
    loginCount: 1,
    loginAttemptError: null,
    lastLogin: null,
    userIdCreated: 1,
    createdTime: new Date(),
    userIdUpdated: 1,
    updatedTime: new Date(),
    isDeleted: false,
    email: 'ops@sicepat.com',
    passwordReset: null,
    otpReset: null,
  },
  {
    id: genId(),
    userId: 16,
    employeeId: 2982,
    firstName: 'General',
    lastName: 'User no Role',
    username: 'general',
    password: 'd8578edf8458ce06fbc5bb76a58c5ca4',
    loginCount: 1,
    loginAttemptError: null,
    lastLogin: null,
    userIdCreated: 1,
    createdTime: new Date(),
    userIdUpdated: 1,
    updatedTime: new Date(),
    isDeleted: false,
    email: 'general@sicepat.com',
    passwordReset: null,
    otpReset: null,
  }
];
