FORMAT: 1A
HOST: http://pettycash.api.url

# API Balance

# Group Balance

## List Balance [GET /v1/balances?balanceDate__lte,branchId,state]

API to get all balance branches (saldo cabang).

+ Parameters
    + balanceDate__lte: `2021-01-01` (date, optional) - Balance Date to filter.
    + branchId: `eaaf465b-65bc-4784-909e-8d0180c6eb4c` (string, optional) - Branch to filter.
    + state (enum[string], optional) - Balance Status to minimum amount.
        + lessThan
        + equal
        + moreThan

+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

+ Response 200 (application/json)
    + Body

        {
            "status": "success",
            "data": [
                {
                    "branchId": "eaaf465b-65bc-4784-909e-8d0180c6eb4c",
                    "branchName": "Tangerang Pinang",
                    "currentAmount": 2000000,
                    "minimumAmount": 2300000,
                    "budgetAmount": 8000000,
                    "differenceAmount": 300000,
                    "state": "lessThan"
                },
                {
                    "branchId": "eaaf465b-65bc-4784-909e-8d0180c6eb4c",
                    "branchName": "Tangerang Pinang",
                    "currentAmount": 2000000,
                    "minimumAmount": 2300000,
                    "budgetAmount": 8000000,
                    "differenceAmount": 300000,
                    "state": "equal"
                }
            ],
            "meta": {
                "page": 2,
                "prevPage": 1,
                "nextPage": null,
                "perPage": 10,
            }
        }

+ Response 500 (application/json)
    + Body

            {
                "status": "error",
                "message": "Internal Server Error"
            }

## Transfer Balance [POST /v1/balances/transfer/{id}]

API untuk transfer saldo dari HO ke Cabang.

+ Parameters
    + id: `d2613fdc-8b7c-486e-90e6-aba5d4a819cb` (string).


+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
        + number:           `TRF20210311QWERTY12` (string) - Transfer Number.
        + branchId:         `28786cd1-bb9e-4926-a332-3a2e1c302e68` (string) - Branch ID.
        + responsibleUserId:`3aa3eac8-a62f-44c3-b53c-31372492f9a0` (string) - Responsible User Id.
        + transferDate:     `d659d65c-fcf3-45c8-956e-5baf9dee2522` (string, optional) - Transferred Date.
        + amount:           `2000000` (number) - Amount.
        + destinationBankId:`28786cd1-bb9e-4926-a332-3a2e1c302e68` (string) - Bank Branch ID.
        + description:      `This is Not Mandatory field` (string, optional) - Description.


+ Response 201 (application/json)
    + Body

        {
            "status": "success",
            "data": {
                "id": "d659d65c-fcf3-45c8-956e-5baf9dee2522",
            }
        }

+ Response 404 (application/json)
    + Body

        {
            "status": "error",
            "message": "ID Saldo Cabang tidak ditemukan!",
            "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
        }

+ Response 500 (application/json)
    + Body

        {
            "status": "error",
            "message": "Internal Error!",
            "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
        }
