FORMAT: 1A
HOST: http://pettycash.api.url

# API Budget Request

# Group Budget Request

## List Budget [GET /v1/budget-requests]

Untuk mendapatkan daftar budget request.

+ Parameters
    + startDate__gte: `2021-02-09` (date, optional) - Searching budget with date range from date start.
    + endDate__gte: `2021-02-15` (date, optional) - Searching budget with date range from end date.
    + branchId: `eaaf465b-65bc-4784-909e-8d0180c6eb4c` (string, optional) - Searching budget by branch id.
    + minAmount__lte: `4000000` (number, optional) - Searching range total amount - min.
    + maxAmount__gte: `8000000` (number, optional) - Searching range total amount - max.
    + state: `draft` (enum, optional) - Searching budget status `draft, approve_by_ops, approve_by_pic, rejected, canceled`
    + order: `-totalAmount` (string, optional) - Sort / order budget by totalAmount ascending.


+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

+ Response 200 (application/json)
    + Body

      "status": "success",
      "data": [
          {
              "id": "d4923882-f5a0-4517-9229-a0d9908a1eb6",
              "branchId": "eaaf465b-65bc-4784-909e-8d0180c6eb4c",
              "budgetId": "04e431ee-058c-4e61-a1a0-f5c7cd21e9f3",
              "branchName": "Tangerang Pinang",
              "number": "BGTR00001",
              "responsibleUserId": "3aa3eac8-a62f-44c3-b53c-31372492f9a0",
              "responsibleUserFirstName": "Adry",
              "responsibleUserLastName": "Adry",
              "responsibleUserUsername": "adry",
              "needDate": "2021-02-09",
              "totalAmount": "7000000",
              "state": "draft",
              "rejectedNote": null
          },
          {
              "id": "d4923882-f5a0-4517-9229-a0d9908a1eb6",
              "branchId": "eaaf465b-65bc-4784-909e-8d0180c6eb4c",
              "budgetId": "04e431ee-058c-4e61-a1a0-f5c7cd21e9f3",
              "branchName": "Bandung",
              "number": "BGTR00001",
              "responsibleUserId": "3aa3eac8-a62f-44c3-b53c-31372492f9a0",
              "responsibleUserFirstName": "Adry",
              "responsibleUserLastName": "Adry",
              "responsibleUserUsername": "adry",
              "needDate": "2021-02-09",
              "totalAmount": "7000000",
              "state": "draft",
              "rejectedNote": null
          }
      ],
      "meta": {
          "page": 1,
          "prevPage": null,
          "nextPage": null,
          "perPage": 10
      }

+ Response 500 (application/json)
    + Body

            {
                "status": "error",
                "message": "Internal Server Error"
            }


## Create Budget Request [POST /v1/budget-requests]

Create Budget Request data

+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
            + branchId: `b7726b7b-6882-42ea-b623-d8f8a347ba0b` (string) - Branch ID.
            + budgetId: `04e431ee-058c-4e61-a1a0-f5c7cd21e9f3` (string) - Budget ID.
            + number: `BG001` (string) - Number.
            + responsibleUserId: "3aa3eac8-a62f-44c3-b53c-31372492f9a0` (string) - User ID.
            + needDate: `2021-01-10` (string) - Need Date.
            + totalAmount: 5000000 (number) - Total Amount.
            + items: (array)
                + productId: `d786c337-39b5-40ab-952b-48cd186027bd` (string) - Product ID.
                + description: `Kebutuhan Pickup` (string) - Description.
                + amount: 1000000 (number) - Amount.

+ Response 201 (application/json)
    + Body

        {
            "status": "success",
            "data": {
                "id": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "branchId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "budgetId": "04e431ee-058c-4e61-a1a0-f5c7cd21e9f3",
                "branchName": "Kebon Jeruk",
                "number": "BG001",
                "responsibleUserId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "responsibleUserFirstName": "Budi",
                "responsibleUserLastName": "Handoko",
                "responsibleUserUsername": 18122009,
                "needDate": "2021-01-29",
                "totalAmount": 5000000,
                "state": "draft",
                "rejectedNote": "Budget melebihi batas minimum"
            }
        }

+ Response 400 (application/json)
    + Body

            {
                "status": "fail",
                "code": "BUDGET_REQUEST_CREATE_FAILED",
                "message": "failed to create budget",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }

+ Response 500 (application/json)
    + Body

            {
                "status": "error",
                "code": "GENERAL_ERROR",
                "message": "Internal Server Error",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }


## Get Budget Request by ID [GET /v1/budget-requests/{id}]

Get Budget Request detail.

+ Parameters
    + id: `46dc5599-43f0-4569-b5f0-33e25f4cd29c` (string) - Budget Reqeuest ID to Retrieve.

+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

+ Response 200 (application/json)
    + Body

        {
          "status": "success",
          "data": {
            "id": "d659d65c-fcf3-45c8-956e-5baf9dee2522",
            "branchId": "3aa3eac8-a62f-44c3-b53c-31372492f9a0",
            "budgetId": "04e431ee-058c-4e61-a1a0-f5c7cd21e9f3",
            "branchName": "Bandung",
            "number": "REL-2020/01/AAB112",
            "responsibleUserId": "3aa3eac8-a62f-44c3-b53c-31372492f9a0",
            "responsibleUserFirstName": "Michael",
            "responsibleUserLastName": "Jordan",
            "responsibleUserUsername": "mjordan",
            "needDate": "2021-01-27",
            "totalAmount": 900000,
            "state": "draft",
            "rejectedNote": "ditolak",
            "items": [
              {
                "id": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "productId": "d786c337-39b5-40ab-952b-48cd186027bd",
                "productName": "Bensin",
                "productCode": "PRD202003AAA111",
                "description": "Kebutuhan Pickup",
                "amount": 1000000,
                "isDeleted": false
              }
            ],
            "histories": [
              {
                "id": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "userId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "userFullName": "Jenny Safitri",
                "userRole": "PIC HO",
                "branchName": "Kebon Jeruk",
                "state": "draft",
                "rejectedNote": "Not OK",
                "createdAt": "2021-03-23T08:22:44.765Z"
              }
            ]
          }
        }

+ Response 404 (application/json)
    + Body

          {
              "status": "fail",
              "code": "BUDGET_REQUEST_NOT_FOUND",
              "message": "budget {id} not found",
              "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
          }

+ Response 500 (application/json)
    + Body

        {
            "status": "error",
            "code": "GENERAL_ERROR",
            "message": "Internal Server Error",
            "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
        }



## Get Budget Data by Need Date [GET /v1/budget-requests/get-budget/{needDate}]

Get Budget detail by Need Date.

+ Parameters
    + needDate: `2021-01-10` (string) - Need Date.

+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

+ Response 200 (application/json)
    + Body

        {
            "status": "success",
            "data": {
                "id": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "branchId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "branchName": "Kebon Jeruk",
                "number": "BG001",
                "responsibleUserId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "responsibleUserFirstName": "Budi",
                "responsibleUserLastName": "Handoko",
                "responsibleUserUsername": 18122009,
                "startDate": "2021-01-29",
                "endDate": "2021-01-29",
                "minimumAmount": 2000000,
                "totalAmount": 5000000,
                "state": "draft",
                "rejectedNote": "Budget melebihi batas minimum"
            }
        }

+ Response 404 (application/json)
    + Body

          {
              "status": "fail",
              "code": "BUDGET_NOT_FOUND",
              "message": "budget {id} not found",
              "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
          }

+ Response 500 (application/json)
    + Body

        {
            "status": "error",
            "code": "GENERAL_ERROR",
            "message": "Internal Server Error",
            "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
        }


## Edit Budget Request [PATCH /v1/budget-requests/{id}/update]

Edit data Budget Request

+ Parameters
    + id: `46dc5599-43f0-4569-b5f0-33e25f4cd29c` (string) - Budget Request ID to Retrieve.

+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
            + branchId: `b7726b7b-6882-42ea-b623-d8f8a347ba0b` (string) - Branch ID.
            + budgetId: `04e431ee-058c-4e61-a1a0-f5c7cd21e9f3` (string) - Budget ID.
            + number: `BGTR001` (string) - Number.
            + responsibleUserId: "3aa3eac8-a62f-44c3-b53c-31372492f9a0` (string) - User ID.
            + needDate: `2021-01-10` (string) - Need Date.
            + totalAmount: 5000000 (number) - Total Amount.
            + items: (array)
                // FOR EDIT BUDGET ITEM
                + id: `c157c304-f9f7-43e6-8084-1d25bfc0d113` (string) - Budget Item ID.
                + productId: `d786c337-39b5-40ab-952b-48cd186027bd` (string) - Product ID.
                + description: `Kebutuhan Pickup` (string) - Description.
                + amount: 1000000 (number) - Amount.
                + isDeleted: false (boolean) - Is Deleted Flag.
                // FOR ADD BUDGET ITEM
                + productId: `d786c337-39b5-40ab-952b-48cd186027bd` (string) - Product ID.
                + description: `Kebutuhan Pickup` (string) - Description.
                + amount: 1000000 (number) - Amount.
                + isDeleted: false (boolean) - Is Deleted Flag
                // FOR DELETE BUDGET ITEM
                + id: `c157c304-f9f7-43e6-8084-1d25bfc0d113` (string) - Budget Item ID.
                + productId: `d786c337-39b5-40ab-952b-48cd186027bd` (string) - Product ID.
                + amount: 1000000 (number) - Amount.
                + isDeleted: true (boolean) - Is Deleted Flag.

+ Response 201 (application/json)
    + Body

        {
            "status": "success",
            "data": {
                "id": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "branchId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "budgetId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "branchName": "Kebon Jeruk",
                "number": "BG001",
                "responsibleUserId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "responsibleUserFirstName": "Budi",
                "responsibleUserLastName": "Handoko",
                "responsibleUserUsername": 18122009,
                "needDate": "2021-01-29",
                "totalAmount": 5000000,
                "state": "draft",
                "rejectedNote": "Budget melebihi batas minimum"
            }
        }

+ Response 400 (application/json)
    + Body

            {
                "status": "fail",
                "code": "BUDGET_REQUEST_EDIT_FAILED",
                "message": "failed to edit budget",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }

+ Response 500 (application/json)
    + Body

            {
                "status": "error",
                "code": "GENERAL_ERROR",
                "message": "Internal Server Error",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }



## Re-Submission Budget Request [PATCH /v1/budget-requests/{id}/re-submission]

Re-Submission data Budget Request

+ Parameters
    + id: `46dc5599-43f0-4569-b5f0-33e25f4cd29c` (string) - Budget Request ID to Retrieve.

+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
            + branchId: `b7726b7b-6882-42ea-b623-d8f8a347ba0b` (string) - Branch ID.
            + budgetId: `04e431ee-058c-4e61-a1a0-f5c7cd21e9f3` (string) - Budget ID.
            + number: `BGTR001` (string) - Number.
            + responsibleUserId: "3aa3eac8-a62f-44c3-b53c-31372492f9a0` (string) - User ID.
            + needDate: `2021-01-10` (string) - Need Date.
            + totalAmount: 5000000 (number) - Total Amount.
            + items: (array)
                // FOR EDIT BUDGET ITEM
                + id: `c157c304-f9f7-43e6-8084-1d25bfc0d113` (string) - Budget Item ID.
                + productId: `d786c337-39b5-40ab-952b-48cd186027bd` (string) - Product ID.
                + description: `Kebutuhan Pickup` (string) - Description.
                + amount: 1000000 (number) - Amount.
                + isDeleted: false (boolean) - Is Deleted Flag.
                // FOR ADD BUDGET ITEM
                + productId: `d786c337-39b5-40ab-952b-48cd186027bd` (string) - Product ID.
                + description: `Kebutuhan Pickup` (string) - Description.
                + amount: 1000000 (number) - Amount.
                + isDeleted: false (boolean) - Is Deleted Flag
                // FOR DELETE BUDGET ITEM
                + id: `c157c304-f9f7-43e6-8084-1d25bfc0d113` (string) - Budget Item ID.
                + productId: `d786c337-39b5-40ab-952b-48cd186027bd` (string) - Product ID.
                + amount: 1000000 (number) - Amount.
                + isDeleted: true (boolean) - Is Deleted Flag.

+ Response 201 (application/json)
    + Body

        {
            "status": "success",
            "data": {
                "id": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "branchId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "budgetId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "branchName": "Kebon Jeruk",
                "number": "BG001",
                "responsibleUserId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                "responsibleUserFirstName": "Budi",
                "responsibleUserLastName": "Handoko",
                "responsibleUserUsername": 18122009,
                "needDate": "2021-01-29",
                "totalAmount": 5000000,
                "state": "draft",
                "rejectedNote": "Budget melebihi batas minimum"
            }
        }

+ Response 400 (application/json)
    + Body

            {
                "status": "fail",
                "code": "BUDGET_REQUEST_RE_SUBMISSION_FAILED",
                "message": "failed to Re-Submission budget",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }

+ Response 500 (application/json)
    + Body

            {
                "status": "error",
                "code": "GENERAL_ERROR",
                "message": "Internal Server Error",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }



## Approve Budget Request [PUT /v1/budget-requests/{id}/approve]

Approve Budget

+ Parameters
    + id: `5343f4f4-36a3-47cc-afe2-01b37a2063bf` (string) - Budget Request ID.

+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

+ Response 200 (application/json)
    + Body

            {
                "status": "success",
                "data": {
                    "id": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                    "branchId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                    "budgetId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                    "branchName": "Kebon Jeruk",
                    "number": "BG001",
                    "responsibleUserId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                    "responsibleUserFirstName": "Budi",
                    "responsibleUserLastName": "Handoko",
                    "responsibleUserUsername": 18122009,
                    "needDate": "2021-01-29",
                    "totalAmount": 5000000,
                    "state": "draft",
                    "rejectedNote": "Budget melebihi batas minimum"
                }
            }

+ Response 400 (application/json)
    + Body

            {
                "status": "fail",
                "code": "BUDGET_REQUEST_APPROVE_FAILED",
                "message": "failed to approve budget",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }

+ Response 500 (application/json)
    + Body

            {
                "status": "error",
                "code": "GENERAL_ERROR",
                "message": "Internal Server Error",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }


## Reject Budget Request [PATCH /v1/budget-requests/{id}/reject]

Reject Budget Request

+ Parameters
    + id: `5343f4f4-36a3-47cc-afe2-01b37a2063bf` (string) - Budget Request ID.

+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
        + rejectedNote: `Salah nominal` (string, required) - Rejected Note.

+ Response 200 (application/json)
    + Body

            {
                "status": "success",
                "data": {
                    "id": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                    "branchId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                    "budgetId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                    "branchName": "Kebon Jeruk",
                    "number": "BG001",
                    "responsibleUserId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                    "responsibleUserFirstName": "Budi",
                    "responsibleUserLastName": "Handoko",
                    "responsibleUserUsername": 18122009,
                    "needDate": "2021-01-29",
                    "totalAmount": 5000000,
                    "state": "draft",
                    "rejectedNote": "Budget melebihi batas minimum"
                }
            }

+ Response 400 (application/json)
    + Body

            {
                "status": "fail",
                "code": "BUDGET_REQUEST_REJECT_FAILED",
                "message": "failed to reject budget",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }

+ Response 500 (application/json)
    + Body

            {
                "status": "error",
                "code": "GENERAL_ERROR",
                "message": "Internal Server Error",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }



## Cancel Budget Request [PATCH /v1/budget-requests/{id}/cancel]

Cancel Budget Request

+ Parameters
    + id: `5343f4f4-36a3-47cc-afe2-01b37a2063bf` (string) - Budget Request ID.

+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

+ Response 200 (application/json)
    + Body

            {
                "status": "success",
                "data": {
                    "id": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                    "branchId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                    "budgetId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                    "branchName": "Kebon Jeruk",
                    "number": "BGTR001",
                    "responsibleUserId": "b7726b7b-6882-42ea-b623-d8f8a347ba0b",
                    "responsibleUserFirstName": "Budi",
                    "responsibleUserLastName": "Handoko",
                    "responsibleUserUsername": 18122009,
                    "needDate": "2021-01-29",
                    "totalAmount": 5000000,
                    "state": "draft",
                    "rejectedNote": "Budget melebihi batas minimum"
                }
            }

+ Response 400 (application/json)
    + Body

            {
                "status": "fail",
                "code": "BUDGET_REQUEST_CANCEL_FAILED",
                "message": "failed to reject budget",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }

+ Response 500 (application/json)
    + Body

            {
                "status": "error",
                "code": "GENERAL_ERROR",
                "message": "Internal Server Error",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }



## Delete Budget Request [PATCH /v1/budget-requests/{id}/delete]

Delete Budget Request

+ Parameters
    + id: `5343f4f4-36a3-47cc-afe2-01b37a2063bf` (string) - Budget Request ID.

+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

+ Response 200 (application/json)
    + Body

+ Response 400 (application/json)
    + Body

            {
                "status": "fail",
                "code": "BUDGET_REQUEST_DELETE_FAILED",
                "message": "failed to delete budget",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }

+ Response 500 (application/json)
    + Body

            {
                "status": "error",
                "code": "GENERAL_ERROR",
                "message": "Internal Server Error",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }