FORMAT: 1A
HOST: http://pettycash.api.url

# API Department

# Group Department

## List Department [GET /v1/departments]

Untuk mendapatkan daftar employee department.

+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

+ Response 200 (application/json)
    + Body

            {
                "data": [
                    {
                        "id": "d2613fdc-8b7c-486e-90e6-aba5d4a819cb",
                        "parent_id": "d2613fdc-8b7c-486e-90e6-aba5d4a819cb",
                        "code": "Admin Branch",
                        "name": "Denny Danuwijaya"
                    }
                ],
                "meta": {
                    "page": 1,
                    "prevPage": 1,
                    "nextPage": null,
                    "perPage": 10,
                },
                "status": "success",
            }

+ Response 500 (application/json)
    + Body

            {
                "status": "error",
                "code": "GENERAL_ERROR",
                "message": "Internal Server Error",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }
