FORMAT: 1A
HOST: http://pettycash.api.url

# API Products

# Group Products

## List Products [GET /v1/products?filter='{name}'&order='{createdAt}']

Untuk mendapatkan daftar product / item.

+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

+ Parameters
    + code: `PR001` (string) - Filtering product by code using method `LIKE`.
    + name: `Tiket Pesawat` (string) - Filtering product by name using method `LIKE`.
    + is_has_tax: true (boolean) - Filtering product by tax having.
    + createdAt: `2021-02-01T13:40:10Z` (timestamp) - Sort / order product by date created.

+ Response 200 (application/json)
    + Body

            {
                "data": [
                    {
                        "id": "d2613fdc-8b7c-486e-90e6-aba5d4a819cb",
                        "code": "PR-00001",
                        "name": "Tiket Pesawat",
                        "description": "Tiket pesawat untuk perjalanan",
                        "is_has_tax": true,
                        "amount": 700000.00,
                        "coa_id": "d2613fdc-8b7c-486e-90e6-aba5d4a819cb",
                        "coaCode": "500.10.11",
                        "coaName": "Cash Transit Coa",
                        "is_active": true
                    },
                    {
                        "id": "d2613fdc-8b7c-486e-90e6-aba5d4a819cb",
                        "code": "PR-00002",
                        "name": "Hotel",
                        "description": "Voucher menginap hotel",
                        "is_has_tax": true,
                        "amount": 350000.00,
                        "coa_id": "d2613fdc-8b7c-486e-90e6-aba5d4a819cb",
                        "coaCode": "500.10.11",
                        "coaName": "Cash Transit Coa",
                        "is_active": true
                    }
                ],
                "meta": {
                    "page": 1,
                    "prevPage": 1,
                    "nextPage": null,
                    "perPage": 10,
                },
                "status": "success",
            }

+ Response 500 (application/json)
    + Body

            {
                "status": "error",
                "code": "GENERAL_ERROR",
                "message": "Internal Server Error",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }

## Create Product [POST /v1/product]

Untuk membuat product / item untuk digunakan pada uang muka, pengeluaran, dll.

+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ

    + Attributes (object)
        + name: `Tiket Pesawat` (string) - Product name.
        + description: `Tiket pesawat untuk perjalanan dinas` (string) - Product Description.
        + isHasTax: true (boolean) - Describe if the product is taxable or not.
        + amount: 750000 (string) - How much amount will be pay for product.
        + coaId: `3e7436b1-adeb-4a85-8676-2968e0cec78c` (string).
        + isActive: true (boolean) - Activate / Disabled the product.

+ Response 200 (application/json)
    + Body

            {
                "status": "success",
                "message": "Product successfully created."
            }

+ Response 400 (application/json)
    + Body

            {
                "status": "fail",
                "code": "PRODUCT_CREATE_FAILED",
                "message": "failed to create product",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }

+ Response 500 (application/json)
    + Body

            {
                "status": "error",
                "code": "GENERAL_ERROR",
                "message": "Internal Server Error",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }

## Update Product [PATCH /v1/product/{id}/update]

Update Product / Item.

+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ
    
    + Attributes (object)
        + name: `Tiket Pesawat` (string) - Product name.
        + description: `Tiket pesawat untuk perjalanan dinas` (string) - Product Description.
        + isHasTax: true (boolean) - Describe if the product is taxable or not.
        + amount: 750000 (string) - How much amount will be pay for product.
        + coaId: `3e7436b1-adeb-4a85-8676-2968e0cec78c` (string).
        + isActive: true (boolean) - Activate / Disabled the product.

+ Parameters
    + id: `d2613fdc-8b7c-486e-90e6-aba5d4a819cb` (string) - UUID of ID to update single product,

+ Response 200 (application/json)
    + Body

            {
                "status": "success",
                "message": "Product successfully updated."
            }

+ Response 400 (application/json)
    + Body

            {
                "status": "fail",
                "code": "PRODUCT_UPDATE_FAILED",
                "message": "failed to update product",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }

+ Response 500 (application/json)
    + Body

            {
                "status": "error",
                "code": "GENERAL_ERROR",
                "message": "Internal Server Error",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }


## Delete Product [DELETE /v1/product/{id}/delete]

Delete Product / Item.

+ Request (application/json)
    + Header

            Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2FwaV9pZCI6MywiZXhwIjoxNTUwMDg4NTE0fQ.Jnp0NMZ05zlXs4mKNdbt7cJ4Xwf8mTZrU-PS_eQY-vQ
    
+ Parameters
    + id: `d2613fdc-8b7c-486e-90e6-aba5d4a819cb` (string) - UUID of ID to delete single product,

+ Response 200 (application/json)
    + Body

            {
                "status": "success",
                "message": "Product successfully deleted."
            }

+ Response 400 (application/json)
    + Body

            {
                "status": "fail",
                "code": "PRODUCT_DELETED_FAILED",
                "message": "failed to delete product",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }

+ Response 500 (application/json)
    + Body

            {
                "status": "error",
                "code": "GENERAL_ERROR",
                "message": "Internal Server Error",
                "traceId": "5343f4f4-36a3-47cc-afe2-01b37a2063bf"
            }


